// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCM89zua1-EAiwJ8IjAaKIjokEx3Ebqc',
    appId: '1:875924720631:web:83a2c12c114e46119e3cf2',
    messagingSenderId: '875924720631',
    projectId: 'ruff-7d37f',
    authDomain: 'ruff-7d37f.firebaseapp.com',
    storageBucket: 'ruff-7d37f.firebasestorage.app',
    measurementId: 'G-T8ZY15VXBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-v0DPbqKSNAOm9CwxFgCUgKu4u5UuN0',
    appId: '1:875924720631:android:d1a799bbc9c7f7cc9e3cf2',
    messagingSenderId: '875924720631',
    projectId: 'ruff-7d37f',
    storageBucket: 'ruff-7d37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHrf78aLFJ3oTXbxe4nCHnCuVw8lrS2I',
    appId: '1:875924720631:ios:38d3881d58f8ebfb9e3cf2',
    messagingSenderId: '875924720631',
    projectId: 'ruff-7d37f',
    storageBucket: 'ruff-7d37f.firebasestorage.app',
    iosClientId: '875924720631-h4q17rm50joigd16ej30niih3gc1smoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjHrf78aLFJ3oTXbxe4nCHnCuVw8lrS2I',
    appId: '1:875924720631:ios:38d3881d58f8ebfb9e3cf2',
    messagingSenderId: '875924720631',
    projectId: 'ruff-7d37f',
    storageBucket: 'ruff-7d37f.firebasestorage.app',
    iosClientId: '875924720631-h4q17rm50joigd16ej30niih3gc1smoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCM89zua1-EAiwJ8IjAaKIjokEx3Ebqc',
    appId: '1:875924720631:web:8e1de5c5c56e18979e3cf2',
    messagingSenderId: '875924720631',
    projectId: 'ruff-7d37f',
    authDomain: 'ruff-7d37f.firebaseapp.com',
    storageBucket: 'ruff-7d37f.firebasestorage.app',
    measurementId: 'G-QKZ3X0L25W',
  );
}
