import 'package:flutter/material.dart';
import 'ruff_home_page.dart'; // Import the file
import 'package:firebase_core/firebase_core.dart';
import 'firebase_option.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false, // Remove debug banner
      home: RuffHomePage(), // Start with RuffHomePage
    );
  }
}

